# Task name - used to pick the class to load
task_name: 'Go2'
# experiment name. defaults to name of training config
experiment: '1'

# chose the env name
env_name: 'rlgpu'

# if set to positive integer
num_envs: 512

# seed - set to -1 to choose random seed
seed: 42

# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: Ture
# used to set checkpoint path
checkpoint: '/home/vieira/isaacgym-project/ME5418_Finalproject/IsaacGymEnvs/isaacgymenvs/outputs1/2024-11-22/14-50-23/runs/1/nn/last_1_ep_250_rew_8583.085.pth'
# Set the standard deviation for exploration noise; leave empty to disable noise
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False

capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True

# disables rendering
headless: False

# Multiple Configuration Files Composition
defaults:
  - task: Go2
  - train: ${task}PPO
  - override hydra/job_logging: disabled # disable hydra logging
  - _self_


